name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: JPPhotoManager 
    - name: Build
      run: dotnet build JPPhotoManager\JPPhotoManager.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test JPPhotoManager\JPPhotoManager.Tests\JPPhotoManager.Tests.csproj --configuration Release --no-build --verbosity normal
