name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore JPPhotoManager/JPPhotoManager.sln
    - name: Build
      run: dotnet build --no-restore --configuration Release JPPhotoManager/JPPhotoManager.sln
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal JPPhotoManager/JPPhotoManager.Tests/JPPhotoManager.Tests.csproj
    - name: Test with coverage
      run: .\test-with-coverage.bat
